### ISSUE TITLE
Publish a new version of the module

### ISSUE THREAD

**Issue by JustinBeckwith** [google/pack-n-play#17]
The module is currently sitting at `0.0.1` on npm, and doesn't have a liink to the repository field.  It would be nice to ship a new version.

**Comment by DominicKramer** [comment]
I'm debating on whether to publish at 1.0.0 so we can use the patch, major, and minor parts unambiguously.  Thoughts?

**Comment by JustinBeckwith** [comment]
Gotcha.  I say:
- Start at 1.0.0-0 
- We iterate through this backlog of issues 
- After it's in a place where I can use it in the `googleapis` modules, we just `1.0.0` it and go from there

I just wanna make sure it's reasonably functional before we 1.0.  @bcoe different day same question about semantic-release :)

**Comment by bcoe** [comment]
I've used the convention `1.0.0-alpha.0`, `1.0.0-alpha.1`, etc; same difference just find it communicates the meaning of the digits after the `-`.

**Comment by JustinBeckwith** [comment]
I just pushed a `1.0.0-2`, which I'm pretty sure is gonna work this time :)
