### ISSUE TITLE
Rename this project

### ISSUE THREAD

**Issue by ofrobots** [google/pack-n-play#22]
See https://github.com/googleapis/nodejs-logging/pull/430#discussion_r267001579

Feedback from various folks has been that the name of this project is confusing – it suggests some relationship to post-install steps. The use-case is very different though: checking that a typescript project can be consumed. It does so by packing the project and installing and using it through npm.

Should we rename this to something like `ts-pack-n-play`?

**Comment by DominicKramer** [comment]
I'm open to changing the name, especially since it is causing confusion.  `ts-pack-n-play` sounds fine to me.

**Comment by JustinBeckwith** [comment]
@ofrobots it would be cool to do this before a 1.0 release.  Any objections to me pushing it forward?

@bencoe do you think `ts-pack-n-play` would be better?  Or do you have a different suggestion?

**Comment by ofrobots** [comment]
Re-mentioning @bcoe because I don't think GitHub pings on edit.

Other suggestions for names that I already have: `ts-consumer-test`. 

🚲🏚

**Comment by JustinBeckwith** [comment]
Ideas!  So for me - I think this package could be about more than just TypeScript.  It's really about validating a package does what you think it should after an `npm pack`, right?  It's just that we often find it useful in the context of TypeScript.  I've also messed up the `files` section in `package.json`, and wished for a test like this. Given that backdrop, ideas!
- `ensure-package-works`
- `does-it-install`
- `pack-n-play`

Just throwing out some thoughts :)
